metrics:
  label: ""
  prometheus:
    use_histogram_timing: false
    histogram_buckets: []
    summary_quantiles_objectives:
      - error: 0.05
        quantile: 0.5
      - error: 0.01
        quantile: 0.9
      - error: 0.001
        quantile: 0.99
    add_process_metrics: false
    add_go_metrics: false
    push_url: "" # No default (optional)
    push_interval: "" # No default (optional)
    push_job_name: benthos_push
    push_basic_auth:
      username: ""
      password: ""
    file_output_path: ""